language: generic

addons:
    apt:
        packages:
        - gfortran-8
        - cmake
        - python-pip
        - graphviz

before_install:
    - pip install --user ford

script:
    - mkdir build
    - cd build
    - FC=gfortran-8 cmake ..
    - make -j
    - cd ..
    - ford fortperc.md
    - rsync -av --exclude src docs/ .
    - rm -rf docs

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
