language: generic

addons:
    apt:
        packages:
        - gfortran
        - cmake
        - python-pip
        - graphviz

before_install:
    - pip install --user ford

script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j
    - cd ..
    - ford fortperc.md
