language: generic

addons:
    apt:
        packages:
        - gfortran
        - cmake
        - python-pip
        - graphviz

before_install:
    - pip install --user ford

script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j
    - cd ..
    - ford fortperc.md

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    on:
        branch: master
